In [45]:
import pandas as pd 
import json

In [46]:
with open('train/_annotations.coco.json') as f:
    data=json.load(f)
data

{'info': {'year': '2024',
  'version': '3',
  'description': 'Exported from roboflow.com',
  'contributor': '',
  'url': 'https://public.roboflow.com/object-detection/undefined',
  'date_created': '2024-11-19T03:14:09+00:00'},
 'licenses': [{'id': 1,
   'url': 'https://creativecommons.org/licenses/by/4.0/',
   'name': 'CC BY 4.0'}],
 'categories': [{'id': 0, 'name': 'wafer-defect', 'supercategory': 'none'},
  {'id': 1, 'name': 'BLOCK ETCH', 'supercategory': 'wafer-defect'},
  {'id': 2, 'name': 'COATING BAD', 'supercategory': 'wafer-defect'},
  {'id': 3, 'name': 'PARTICLE', 'supercategory': 'wafer-defect'},
  {'id': 4, 'name': 'PIQ PARTICLE', 'supercategory': 'wafer-defect'},
  {'id': 5, 'name': 'PO CONTAMINATION', 'supercategory': 'wafer-defect'},
  {'id': 6, 'name': 'SCRATCH', 'supercategory': 'wafer-defect'},
  {'id': 7, 'name': 'SEZ BURNT', 'supercategory': 'wafer-defect'}],
 'images': [{'id': 0,
   'license': 1,
   'file_name': '18065_image1_resize_JPG.rf.00aa9fbf09b0f3007cc2a08b8eae750c.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 1,
   'license': 1,
   'file_name': '14019_image2_resize_JPG.rf.01fd438b49166f558a5fe04ae2277cd7.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 2,
   'license': 1,
   'file_name': '20145_image1_resize_JPG.rf.01a8392e77a9cb8576c8fed4d13be2e2.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 3,
   'license': 1,
   'file_name': '11257_image1_resize_JPG.rf.00c9f974b67778f931784b2171509ccf.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 4,
   'license': 1,
   'file_name': '10345_image1_resize_JPG.rf.037f1e159061624f7ed23ac6a4e28ef0.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 5,
   'license': 1,
   'file_name': '20250_image2_resize_JPG.rf.03bbc0539238e386ca3dceae1186c6f9.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 6,
   'license': 1,
   'file_name': '20185_image1_jpg.rf.01c4d1aef0d3bcfa5f5e30dd4ec1494a.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 7,
   'license': 1,
   'file_name': '1034_image2_jpg.rf.03d5fbf3b50cd9e648f51b6a8c76b576.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 8,
   'license': 1,
   'file_name': '13720_image1_jpg.rf.00e0daa8b3ddb9a5a45218c030386783.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 9,
   'license': 1,
   'file_name': '19137_image1_jpg.rf.0357539d2d6a40b1b74d163b553e87eb.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 10,
   'license': 1,
   'file_name': '16718_image2_jpg.rf.036ac4e5d7551d40204fad156daaf053.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 11,
   'license': 1,
   'file_name': '15186_image2_jpg.rf.02c7df002ae46a2cfa514a78299800a1.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 12,
   'license': 1,
   'file_name': '18474_image1_resize_JPG.rf.0366b39387faa2b72d58e53c4132b4c6.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 13,
   'license': 1,
   'file_name': '16996_image2_jpg.rf.0478d68dd394da1974d9cf63f40b9907.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 14,
   'license': 1,
   'file_name': '1527_image1_jpg.rf.027670003e044d366f86963312783290.jpg',
   'height': 555,
   'width': 740,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 15,
   'license': 1,
   'file_name': '19818_image2_resize_JPG.rf.02d941fa61960001be701c4a46992d1c.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 16,
   'license': 1,
   'file_name': '15853_image2_jpg.rf.04a01241c36a9266d957dd23f87ab41e.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 17,
   'license': 1,
   'file_name': '19777_image1_jpg.rf.01c2d7121c268f1de8d004de0422993c.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 18,
   'license': 1,
   'file_name': '15773_image2_jpg.rf.054e825b09093ad801377597c4ddc600.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 19,
   'license': 1,
   'file_name': '16898_image1_resize_JPG.rf.02202c422976dd790669e17061ba419a.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 20,
   'license': 1,
   'file_name': '18124_image2_resize_JPG.rf.02b644ae97fdf10ebd900ea4b752a885.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 21,
   'license': 1,
   'file_name': '10284_image5_jpg.rf.03d5ac173caba0bacbb66a1f05c990d6.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 22,
   'license': 1,
   'file_name': '19222_image2_jpg.rf.010c6099e2721fba683eb6fe965faad4.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 23,
   'license': 1,
   'file_name': '1703_image2_jpg.rf.04ee21cf34210a0c848e305d9c60248d.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 24,
   'license': 1,
   'file_name': '10870_image1_resize_JPG.rf.03fd1b985ca4fc7f15351086834fc736.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 25,
   'license': 1,
   'file_name': '14068_image1_jpg.rf.058597313f55aad6b41397e70d8695b2.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 26,
   'license': 1,
   'file_name': '18303_image1_resize_JPG.rf.05994df22816c554ca261d65480c2138.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 27,
   'license': 1,
   'file_name': '21277_image1_jpg.rf.0229f5085d2f49a71478f1ac2e8e1275.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 28,
   'license': 1,
   'file_name': '1691_image1_jpg.rf.055ed01a82525cec805a5d43d41215f4.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 29,
   'license': 1,
   'file_name': '18425_image2_jpg.rf.0583944dc9217070cc81563615c495e9.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 30,
   'license': 1,
   'file_name': '14986_image1_resize_JPG.rf.06651bcbfc21c639f458b52be6f00d7e.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 31,
   'license': 1,
   'file_name': '18954_image2_jpg.rf.061bd31cc9545ae4b8e4ef3da9090a30.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 32,
   'license': 1,
   'file_name': '13320_image2_jpg.rf.06f653a896253d9860b014a1d9b29dc6.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 33,
   'license': 1,
   'file_name': '183_image3_jpg.rf.05e22efc5b52913f40e3089b06227a1c.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 34,
   'license': 1,
   'file_name': '13320_image1_jpg.rf.06edccc237490620df4fe2beac7b11d4.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 35,
   'license': 1,
   'file_name': '20021_image2_jpg.rf.08dcb1732652a17cebbdafbe0e5e62b2.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 36,
   'license': 1,
   'file_name': '14559_image1_jpg.rf.07077d1e00604a6822387165371f240c.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 37,
   'license': 1,
   'file_name': '15361_image1_resize_JPG.rf.088fc9eff77336a1dd6d8ba6002a6cc2.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 38,
   'license': 1,
   'file_name': '14040_image1_jpg.rf.088212703850af0ddb58d761e1e3b243.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 39,
   'license': 1,
   'file_name': '1675_image1_jpg.rf.080047b1cde0646f9e82a399db897b34.jpg',
   'height': 543,
   'width': 982,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 40,
   'license': 1,
   'file_name': '13413_image3_jpg.rf.07a7a80d422ca57136f8319cebc6c1bc.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 41,
   'license': 1,
   'file_name': '11591_image3_jpg.rf.05bc08db7e52c2480e11dbd5e4a5bbbf.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 42,
   'license': 1,
   'file_name': '15910_image1_resize_JPG.rf.084ade13d04e3481d1a166f7ad939fb5.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 43,
   'license': 1,
   'file_name': '15850_image1_jpg.rf.05d2b2ce509bb7fce7557fead5ced31d.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 44,
   'license': 1,
   'file_name': '16063_image1_jpg.rf.075c17f7d88d98ca70bda72942710c82.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 45,
   'license': 1,
   'file_name': '17414_image2_jpg.rf.08ffa61a56b150f921f478624f7d23a9.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 46,
   'license': 1,
   'file_name': '163_image1_resize_JPG.rf.088cb4a309af5ca6fbaeeccdc8ed3d87.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 47,
   'license': 1,
   'file_name': '20412_image2_resize_JPG.rf.0931dd2f6c1baca5ea3617897c3aa616.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 48,
   'license': 1,
   'file_name': '15943_image1_jpg.rf.0934424fa2b86099111279afc1bb9fd7.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 49,
   'license': 1,
   'file_name': '15905_image1_jpg.rf.065c2abe776bb394d11d210793fe0a92.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 50,
   'license': 1,
   'file_name': '15761_image1_jpg.rf.091513a9e86cb8784e3f197570e544ab.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 51,
   'license': 1,
   'file_name': '20344_image1_resize_JPG.rf.0701df654582483879b4bdbc7514153a.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 52,
   'license': 1,
   'file_name': '15411_image1_jpg.rf.098faae399745dfc133875e8fd5ac4af.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 53,
   'license': 1,
   'file_name': '17438_image1_jpg.rf.09d507ec02f66da233635f59b452a289.jpg',
   'height': 450,
   'width': 600,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 54,
   'license': 1,
   'file_name': '19001_image1_jpg.rf.0956528af28dadeeba5c092501f500d8.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 55,
   'license': 1,
   'file_name': '16642_image2_jpg.rf.095cf8f59917b211fc177c26e7673e23.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 56,
   'license': 1,
   'file_name': '11579_image1_jpg.rf.09aee83c8978f3b8daaa3233e6ab8ca2.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 57,
   'license': 1,
   'file_name': '10617_image1_jpg.rf.097557e06eb038f6d63af34cd8044a1a.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 58,
   'license': 1,
   'file_name': '1098_image3_jpg.rf.08dcfbbc1c8d19a168c92646e5703aaa.jpg',
   'height': 231,
   'width': 427,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 59,
   'license': 1,
   'file_name': '12753_image1_jpg.rf.0a4dd2b464f1efcd8a1d1b8dda7b00f8.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 60,
   'license': 1,
   'file_name': '20155_image1_jpg.rf.0b725608c5a01e00346ad422c4ab3122.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 61,
   'license': 1,
   'file_name': '17691_image1_resize_JPG.rf.0b855719cd338c23dfbb71ed3b0894e1.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 62,
   'license': 1,
   'file_name': '14537_image3_jpg.rf.0d321c725b25ae015d4042ab45c08ee4.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 63,
   'license': 1,
   'file_name': '12425_image1_jpg.rf.0c496a3c875a6d75905c4d389dc2eb0f.jpg',
   'height': 433,
   'width': 759,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 64,
   'license': 1,
   'file_name': '13022_image6_jpg.rf.0c00eb985216558d386755ca34c1b06a.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 65,
   'license': 1,
   'file_name': '15317_image1_jpg.rf.0c5548c4f5f64a772be679b2b7df8108.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 66,
   'license': 1,
   'file_name': '18139_image1_jpg.rf.0cdc29341ea62fdd5b0b5b4a4e82785a.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 67,
   'license': 1,
   'file_name': '10034_image9_resize_JPG.rf.0c39eddf12dd82f43bccfd06d02a5484.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 68,
   'license': 1,
   'file_name': '20203_image1_jpg.rf.09da96fbb4a6553b81927b9dd64c79a6.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 69,
   'license': 1,
   'file_name': '20385_image1_jpg.rf.0d369bd61e9c092413cf7df0c03b52c9.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 70,
   'license': 1,
   'file_name': '14821_image3_jpg.rf.0b7cb7a4116edda7ea347ef7b7e4bd39.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 71,
   'license': 1,
   'file_name': '18289_image2_jpg.rf.0da4e4ab783c9ebf56347c71808daf7a.jpg',
   'height': 512,
   'width': 512,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 72,
   'license': 1,
   'file_name': '20507_image1_jpg.rf.0ba52e0b6e47a7719ed664ae80606af7.jpg',
   'height': 512,
   'width': 512,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 73,
   'license': 1,
   'file_name': '10253_image1_jpg.rf.0b22d79e5cc79eb123e8f091142ae856.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 74,
   'license': 1,
   'file_name': '17434_image1_jpg.rf.0d0f64a47077906d58b46d09fc62effd.jpg',
   'height': 450,
   'width': 600,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 75,
   'license': 1,
   'file_name': '13751_image1_resize_JPG.rf.0e29b3a55a9217378268e1262e226cfc.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 76,
   'license': 1,
   'file_name': '10607_image2_resize_JPG.rf.0d837f345b44de85807ef7e5107b0d9e.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 77,
   'license': 1,
   'file_name': '15082_image1_jpg.rf.0dd577f814b66b8a0cc3e81a0c2ae6ee.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 78,
   'license': 1,
   'file_name': '13212_image2_jpg.rf.0c7869922e582d60445d1a2cdb2c8495.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 79,
   'license': 1,
   'file_name': '19924_image3_jpg.rf.0e66da14ed2fd43495f13f935a13b99b.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 80,
   'license': 1,
   'file_name': '17659_image1_resize_JPG.rf.0bef1250d81363bcf70490bd8d61e74a.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 81,
   'license': 1,
   'file_name': '13212_image1_jpg.rf.0c23b2fd4007a41088d03aeb24d29f50.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 82,
   'license': 1,
   'file_name': '10524_image1_resize_JPG.rf.0d333362176e2ecd5f19c42f9c5d864c.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 83,
   'license': 1,
   'file_name': '15411_image2_jpg.rf.0e5b9273cc8704d1e539917baab15a24.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 84,
   'license': 1,
   'file_name': '12809_image1_resize_JPG.rf.0e6b4b141f6601e739b19155dd83dbb8.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 85,
   'license': 1,
   'file_name': '18848_image1_resize_JPG.rf.0e79b7e9fb57e575efddebdb35fa5526.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 86,
   'license': 1,
   'file_name': '17178_image1_jpg.rf.0ed20b7739da43ca9b1a9be36c5f7470.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 87,
   'license': 1,
   'file_name': '15026_image1_jpg.rf.0ff4d5bdb9081c25944e76d8ae0587df.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 88,
   'license': 1,
   'file_name': '19549_image1_jpg.rf.0f185ced24366df3655fa952e62a59fc.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 89,
   'license': 1,
   'file_name': '20348_image1_jpg.rf.1119e2c5f99e074ccaeeaf65f6c8cbd5.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 90,
   'license': 1,
   'file_name': '16931_image1_resize_JPG.rf.0fbd0901756a866540975802ebd124a9.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 91,
   'license': 1,
   'file_name': '19691_image1_resize_JPG.rf.0f7fa00cef2a3562ce1e77f912f7f33d.jpg',
   'height': 224,
   'width': 224,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 92,
   'license': 1,
   'file_name': '20342_image1_jpg.rf.10deb1c61327c60942974c69f8337099.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 93,
   'license': 1,
   'file_name': '11557_image2_jpg.rf.105b5414ce44eeaa19534333c971cc93.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 94,
   'license': 1,
   'file_name': '19759_image1_jpg.rf.0efbab625beeb30661dd85f215b70e39.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 95,
   'license': 1,
   'file_name': '14839_image1_jpg.rf.10073f36c61ac0cb44ef7444b38b0187.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 96,
   'license': 1,
   'file_name': '19499_image1_jpg.rf.10f44e56fc5fba36d9ca0616e418a3d8.jpg',
   'height': 576,
   'width': 742,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 97,
   'license': 1,
   'file_name': '15167_image3_jpg.rf.104b737bd1e2def92f1ca4e13ec64101.jpg',
   'height': 480,
   'width': 640,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 98,
   'license': 1,
   'file_name': '1101_image2_jpg.rf.0fae743931fc43f8dff13c5f87e39655.jpg',
   'height': 555,
   'width': 740,
   'date_captured': '2024-11-19T03:14:09+00:00'},
  {'id': 99,

In [47]:
data.keys()

dict_keys(['info', 'licenses', 'categories', 'images', 'annotations'])

In [48]:
data['categories']
df_cat=pd.DataFrame(data['categories'])
df_cat

   id              name supercategory
0   0      wafer-defect          none
1   1        BLOCK ETCH  wafer-defect
2   2       COATING BAD  wafer-defect
3   3          PARTICLE  wafer-defect
4   4      PIQ PARTICLE  wafer-defect
5   5  PO CONTAMINATION  wafer-defect
6   6           SCRATCH  wafer-defect
7   7         SEZ BURNT  wafer-defect

In [49]:
df_images=pd.DataFrame(data['images'])
df_images

,id,license,file_name,height,width,date_captured
0,0,1,18065_image1_resize_JPG.rf.00aa9fbf09b0f3007cc...,224,224,2024-11-19T03:14:09+00:00
1,1,1,14019_image2_resize_JPG.rf.01fd438b49166f558a5...,224,224,2024-11-19T03:14:09+00:00
2,2,1,20145_image1_resize_JPG.rf.01a8392e77a9cb8576c...,224,224,2024-11-19T03:14:09+00:00
3,3,1,11257_image1_resize_JPG.rf.00c9f974b67778f9317...,224,224,2024-11-19T03:14:09+00:00
4,4,1,10345_image1_resize_JPG.rf.037f1e159061624f7ed...,224,224,2024-11-19T03:14:09+00:00
...,...,...,...,...,...,...
1594,1594,1,19087_image2_jpg.rf.fd72378d0613cf9577e759f030...,576,742,2024-11-19T03:14:09+00:00
1595,1595,1,1247_image1_jpg.rf.ff19081c2a10cdeb8ccf15330ac...,790,1444,2024-11-19T03:14:09+00:00
1596,1596,1,1287_image3_jpg.rf.ff1d342cb4071722fc51f1731f0...,520,693,2024-11-19T03:14:09+00:00
1597,1597,1,19146_image3_jpg.rf.ff7b952050db22667301772daa...,576,742,2024-11-19T03:14:09+00:00
1598,1598,1,14972_image2_jpg.rf.fe330bb01d1d056a7dbcb5bef6...,576,742,2024-11-19T03:14:09+00:00

In [50]:
df_a=pd.DataFrame(data['annotations'])
df_a

,id,image_id,category_id,bbox,area,segmentation,iscrowd
0,0,0,3,"[61, 79, 91, 98.3]",8945.30,"[[106.7, 79.1, 99, 78.6, 91.6, 80.5, 78.5, 90....",0
1,1,1,3,"[114, 165, 23.1, 22.2]",512.82,"[[114.7, 180.5, 121.1, 186.9, 130.4, 186.9, 13...",0
2,2,2,3,"[75, 79, 64.5, 64.8]",4179.60,"[[137.9, 96.7, 132.9, 87, 126.3, 81.2, 118.1, ...",0
3,3,3,3,"[45, 37, 137, 168.8]",23125.60,"[[72.5, 36.5, 69.5, 38.5, 66.5, 37.5, 66.5, 39...",0
4,4,4,3,"[70, 73, 52.8, 79]",4171.20,"[[100.7, 73.1, 86.2, 77.1, 82.2, 81.2, 80.3, 9...",0
...,...,...,...,...,...,...,...
1621,1621,1594,6,"[300, 287, 441.6, 138.2]",61029.12,"[[742, 292.738, 740.8, 289.8, 733.7, 286.9, 71...",0
1622,1622,1595,4,"[596, 389, 52, 52]",2704.00,"[[598.2, 425.3, 603.8, 433.5, 612.1, 439.1, 62...",0
1623,1623,1596,6,"[105, 203, 581.4, 316.6]",184071.24,"[[178.51, 520, 184.6, 517.9, 187.6, 510.9, 184...",0
1624,1624,1597,6,"[128, 166, 312.2, 222.4]",69433.28,"[[128.7, 182.8, 139.4, 193, 135.9, 197.1, 134....",0
1625,1625,1598,6,"[128, 0, 447.6, 509.7]",228141.72,"[[237.139, 0, 223.145, 0, 222.9, 0.1, 220, 7.2...",0

In [51]:
df_a['segmentation'][0]

[[106.7,
  79.1,
  99,
  78.6,
  91.6,
  80.5,
  78.5,
  90.5,
  69.1,
  105.6,
  61.1,
  128.8,
  62.1,
  137.2,
  67.9,
  148.3,
  76.3,
  159,
  91.3,
  172.4,
  104.3,
  176.9,
  117.5,
  174.5,
  124.8,
  169.7,
  147.4,
  145.1,
  151.2,
  137.1,
  152.1,
  131.1,
  150.3,
  121.5,
  143.2,
  109.9,
  120.7,
  85.8,
  109.8,
  79.9,
  106.7,
  79.1]]

In [52]:
df_a['category_id'].unique()

array([3, 6, 5, 2, 4, 7, 1])

In [53]:
with open('temp/wafer.v2-2024-05-25-1-27am.coco/train/_annotations.coco.json', 'r') as f:
    nd=json.load(f)
nd

{'info': {'year': '2024',
  'version': '2',
  'description': 'Exported from roboflow.com',
  'contributor': '',
  'url': 'https://public.roboflow.com/object-detection/undefined',
  'date_created': '2024-07-20T03:26:41+00:00'},
 'licenses': [{'id': 1,
   'url': 'https://creativecommons.org/licenses/by/4.0/',
   'name': 'CC BY 4.0'}],
 'categories': [{'id': 0,
   'name': 'Bridge-Particle-Scratch',
   'supercategory': 'none'},
  {'id': 1, 'name': 'bridge', 'supercategory': 'Bridge-Particle-Scratch'},
  {'id': 2, 'name': 'particle', 'supercategory': 'Bridge-Particle-Scratch'},
  {'id': 3, 'name': 'scratch', 'supercategory': 'Bridge-Particle-Scratch'}],
 'images': [{'id': 0,
   'license': 1,
   'file_name': '20240524_213028_jpg.rf.e3c7960bcf16ee8f775287e7ace27083.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 1,
   'license': 1,
   'file_name': '20240524_205743_jpg.rf.ebcc27d5f99c602c17cedcbdb62f6cdf.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 2,
   'license': 1,
   'file_name': '20240524_213016_jpg.rf.ef9d8435863084fa859ed32f3f3c8c54.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 3,
   'license': 1,
   'file_name': '20240524_205838_jpg.rf.e3cb570d6bfbd39cced27d560930aee0.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 4,
   'license': 1,
   'file_name': '20240524_212919_jpg.rf.e142a217cc44e1037fef4fde37770c9c.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 5,
   'license': 1,
   'file_name': '20240524_205726_jpg.rf.e4bf0e966f5b5fbc473f936f23981d53.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 6,
   'license': 1,
   'file_name': '20240524_205756_jpg.rf.e9a98e1f2f7bb05367ba7ff0d24591d5.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 7,
   'license': 1,
   'file_name': '20240524_204628_jpg.rf.f7cf5ee1aa8ba1b08a69e28119802a6b.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 8,
   'license': 1,
   'file_name': '20240524_212925_jpg.rf.f0843a9d2de93a552ef2167af3095048.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 9,
   'license': 1,
   'file_name': '20240524_204513_jpg.rf.f40616a01555ed18fe9f796493b33ad4.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 10,
   'license': 1,
   'file_name': '20240524_212106_jpg.rf.e2909769531a6925e6dd0faf9abdcf35.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 11,
   'license': 1,
   'file_name': '20240524_213459_jpg.rf.e86475ca5ff752c165b2b1c63ffe5bd4.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 12,
   'license': 1,
   'file_name': '20240524_210607_jpg.rf.f61405790b5494697938260dbef66e19.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 13,
   'license': 1,
   'file_name': '20240524_205726_jpg.rf.e163c4cf36e95d2a94606e74bacf7ef4.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 14,
   'license': 1,
   'file_name': '20240524_205831_jpg.rf.f7af2c3fc500c354c09585fa74f41ebb.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 15,
   'license': 1,
   'file_name': '20240524_213418_jpg.rf.f4866af52a3a5f74f9b5a641735360fe.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 16,
   'license': 1,
   'file_name': '20240524_204513_jpg.rf.f80ac574f0621d91d5ebc7505e7d8079.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 17,
   'license': 1,
   'file_name': '20240524_213028_jpg.rf.f06825d901eec6df426d437b71dc1f80.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 18,
   'license': 1,
   'file_name': '20240524_213222_jpg.rf.eee075308d786a38669e57f5f0bb7b9e.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 19,
   'license': 1,
   'file_name': '20240524_213418_jpg.rf.f7d5e2c15a7aa4e8d17d9ec77c90f70c.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 20,
   'license': 1,
   'file_name': '20240524_213400_jpg.rf.e4734423745571d4e1785be28c828485.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 21,
   'license': 1,
   'file_name': '20240524_204519_jpg.rf.f38d4698f6b4881a285532709bef4778.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 22,
   'license': 1,
   'file_name': '20240524_213235_jpg.rf.e162c9372f8cf689736a8f3f15b97919.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 23,
   'license': 1,
   'file_name': '20240524_204808_jpg.rf.e95bad70f3b57efdd3f957d2e3d70c2e.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 24,
   'license': 1,
   'file_name': '20240524_210619_jpg.rf.ea9c9e02adc2d7e631b81264eacaa822.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 25,
   'license': 1,
   'file_name': '20240524_204837_jpg.rf.f8b936cfe4d0083dde67fc96c14e3671.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 26,
   'license': 1,
   'file_name': '20240524_204542_jpg.rf.f8eccfcac6fb2fe50c74ce01d269b8a3.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 27,
   'license': 1,
   'file_name': '20240524_213447_jpg.rf.f956f5fcae857a304e099a754a1efae6.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 28,
   'license': 1,
   'file_name': '20240524_212158_jpg.rf.fc710295062bbc7a25141c996afd024f.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 29,
   'license': 1,
   'file_name': '20240524_213016_jpg.rf.fb5cc2445b99e9a2c1baf09de1ebe4a8.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 30,
   'license': 1,
   'file_name': '20240524_204837_jpg.rf.ffd807013ac9165bd46643a63673ef08.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 31,
   'license': 1,
   'file_name': '20240524_213436_jpg.rf.f96516a85221980ed8d30958064192e0.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 32,
   'license': 1,
   'file_name': '20240524_204832_jpg.rf.faba57e5ee2eefcd72c8cdcf7be200be.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 33,
   'license': 1,
   'file_name': '20240524_205855_jpg.rf.fbb757c5aef5817649b3f50638e5679a.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 34,
   'license': 1,
   'file_name': '20240524_212049_jpg.rf.ff8c0df230eac54565897e17166ef455.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 35,
   'license': 1,
   'file_name': '20240524_212112_jpg.rf.fc5e0cd5e147926e57c7f150b706e6e9.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 36,
   'license': 1,
   'file_name': '20240524_213033_jpg.rf.03464f46c49f4d9963ecce91c1d8e40f.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 37,
   'license': 1,
   'file_name': '20240524_212341_jpg.rf.060f4ac6f5d35d2e15a154caf2b9071e.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 38,
   'license': 1,
   'file_name': '20240524_212112_jpg.rf.0b61949c7766810f501f97e84ce1f474.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 39,
   'license': 1,
   'file_name': '20240524_213229_jpg.rf.0b37c4dacc10c90b00b351608991cb12.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 40,
   'license': 1,
   'file_name': '20240524_212244_jpg.rf.02ff23b918d6f9c497064c9f76c2584d.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 41,
   'license': 1,
   'file_name': '20240524_205814_jpg.rf.020f164b1df3b86876a4d658bbf4e7b2.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 42,
   'license': 1,
   'file_name': '20240524_204519_jpg.rf.09e38b8867574e8ea972d1feac60acf2.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 43,
   'license': 1,
   'file_name': '20240524_204507_jpg.rf.0b607406edd41d5128315fd086e9ff2b.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 44,
   'license': 1,
   'file_name': '20240524_213217_jpg.rf.0a2f7e0563e5de621ab7dac0237bd868.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 45,
   'license': 1,
   'file_name': '20240524_204513_jpg.rf.0617e4e12705dd6d7ca3a077320597a0.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 46,
   'license': 1,
   'file_name': '20240524_212054_jpg.rf.0c6d930506474e9459ac3f545da4187f.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 47,
   'license': 1,
   'file_name': '20240524_213418_jpg.rf.0d8a6fcc62ade56229b008d002b2e4a4.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 48,
   'license': 1,
   'file_name': '20240524_204808_jpg.rf.0d0477caf220f9488fbb8c0d8fbb57b5.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 49,
   'license': 1,
   'file_name': '20240524_210607_jpg.rf.0338d7d5063c8cf462ff7c8c8b882c47.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 50,
   'license': 1,
   'file_name': '20240524_204605_jpg.rf.02ca3c0f968620961f1cc0eb907823f6.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 51,
   'license': 1,
   'file_name': '20240524_205825_jpg.rf.10141a0f84b496dcb8ea5293f9b60b11.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 52,
   'license': 1,
   'file_name': '20240524_204634_jpg.rf.109db78b7ba437d483aa8c762901c2c3.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 53,
   'license': 1,
   'file_name': '20240524_212054_jpg.rf.10c2dbddd5ae8be292289bc31e14ad68.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 54,
   'license': 1,
   'file_name': '20240524_213344_jpg.rf.1118221def87544d74c8316d5d18060e.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 55,
   'license': 1,
   'file_name': '20240524_213217_jpg.rf.12b0812cccb03a9a5774dcf3d79c0fdd.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 56,
   'license': 1,
   'file_name': '20240524_204617_jpg.rf.21daa484ffc9d36cf155db24ec02cad8.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 57,
   'license': 1,
   'file_name': '20240524_204547_jpg.rf.1705e64143a2bc09bb0a7efd76c65ff6.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 58,
   'license': 1,
   'file_name': '20240524_213222_jpg.rf.10f37077ca4e64396e06f174eade3b56.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 59,
   'license': 1,
   'file_name': '20240524_204826_jpg.rf.1e49978d2b1551a256fb85274f996aa5.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 60,
   'license': 1,
   'file_name': '20240524_213447_jpg.rf.1b2fbb6033a08b8df9b8bbb3adae7245.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 61,
   'license': 1,
   'file_name': '20240524_204726_jpg.rf.22cea52609a53d1239f1d09f091080ff.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 62,
   'license': 1,
   'file_name': '20240524_210711_jpg.rf.1f42597c7e924327ecdfdd163c59b271.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 63,
   'license': 1,
   'file_name': '20240524_205801_jpg.rf.278b93110f2eb2f8aaf632977acdea39.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 64,
   'license': 1,
   'file_name': '20240524_212140_jpg.rf.22e205330487848cb0bc9f7f2c75c016.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 65,
   'license': 1,
   'file_name': '20240524_212255_jpg.rf.122f9904ac3d79a18ce1cb7fa2003644.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 66,
   'license': 1,
   'file_name': '20240524_213229_jpg.rf.272d6e05eece08ea5ebf6ce4628a2ef2.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 67,
   'license': 1,
   'file_name': '20240524_212101_jpg.rf.112626586b490e299f75b683df87c60f.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 68,
   'license': 1,
   'file_name': '20240524_212049_jpg.rf.26bafe8eb0faa935ebe8069198b41eb7.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 69,
   'license': 1,
   'file_name': '20240524_205732_jpg.rf.275343f174529ea628d9b6a00a3f6fca.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 70,
   'license': 1,
   'file_name': '20240524_205844_jpg.rf.21a75b7b06318391e822cc257e830e02.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 71,
   'license': 1,
   'file_name': '20240524_204628_jpg.rf.1edd0bf0922123cf0f7e9d6424243682.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 72,
   'license': 1,
   'file_name': '20240524_205756_jpg.rf.23f5215817af3db82d112fe190237745.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 73,
   'license': 1,
   'file_name': '20240524_210705_jpg.rf.19538d454006c7f2026921002f0eb124.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 74,
   'license': 1,
   'file_name': '20240524_213423_jpg.rf.21ec5afa344fa8285cbd08cb70ca4c9e.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 75,
   'license': 1,
   'file_name': '20240524_204605_jpg.rf.2772fa0939fd22a141f23a7795a6da7a.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 76,
   'license': 1,
   'file_name': '20240524_213407_jpg.rf.1ea160a72546e60ef997a1318946059c.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 77,
   'license': 1,
   'file_name': '20240524_213010_jpg.rf.2889100a046c02818253a5412c2a25aa.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 78,
   'license': 1,
   'file_name': '20240524_212043_jpg.rf.28a4f7fc4823346f3350a1731da77048.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 79,
   'license': 1,
   'file_name': '20240524_210607_jpg.rf.23a76e95dae12640fecacf968269abb8.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 80,
   'license': 1,
   'file_name': '20240524_204731_jpg.rf.2368a35dbcea504a970b63818ae2c68c.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 81,
   'license': 1,
   'file_name': '20240524_205814_jpg.rf.30db4eef7b758408c0f8afb6b71ed4a0.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 82,
   'license': 1,
   'file_name': '20240524_212919_jpg.rf.2ee1c377f9db5457ba64754d15e64909.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 83,
   'license': 1,
   'file_name': '20240524_212244_jpg.rf.340dea3637221fa91cd0faaefcf3b8b6.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 84,
   'license': 1,
   'file_name': '20240524_213412_jpg.rf.28f46d5168ff741f9e558c2f10ec61a8.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 85,
   'license': 1,
   'file_name': '20240524_212158_jpg.rf.37d7a03ee011bf2e9bbd84ca7e7e82c3.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 86,
   'license': 1,
   'file_name': '20240524_213246_jpg.rf.317453ab5615443886c15330538b0f9e.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 87,
   'license': 1,
   'file_name': '20240524_204628_jpg.rf.39b7b35623108e1f589dd47df588cfc5.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 88,
   'license': 1,
   'file_name': '20240524_205807_jpg.rf.3490fca6a1792d44987030ef01e338a7.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 89,
   'license': 1,
   'file_name': '20240524_213212_jpg.rf.3aa05c5a509c0824a7af6732ac6b5a00.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 90,
   'license': 1,
   'file_name': '20240524_213000_jpg.rf.3c55a9c980ba4da0e2a21acf34f3495a.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 91,
   'license': 1,
   'file_name': '20240524_213235_jpg.rf.3ee7b921462b943c8f747a18c64fd6c3.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 92,
   'license': 1,
   'file_name': '20240524_204726_jpg.rf.34c052286ec1f42c0e99453bcb7b7c68.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 93,
   'license': 1,
   'file_name': '20240524_204802_jpg.rf.40155f623cc589e2bc5e1a8895385534.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 94,
   'license': 1,
   'file_name': '20240524_210734_jpg.rf.31ae4c8d0e8df9e3afa278ea7893f780.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 95,
   'license': 1,
   'file_name': '20240524_204524_jpg.rf.3506a4246f4604d409ea49abb67775ce.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 96,
   'license': 1,
   'file_name': '20240524_204507_jpg.rf.367a65edd672b67ec2c6956002acd4b0.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 97,
   'license': 1,
   'file_name': '20240524_212054_jpg.rf.2f1841b6b372b23408816e6c1c66b9b0.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 98,
   'license': 1,
   'file_name': '20240524_212135_jpg.rf.4263607a2de7ea728ab424d16aa9674e.jpg',
   'height': 640,
   'width': 640,
   'date_captured': '2024-07-20T03:26:41+00:00'},
  {'id': 99,
   'license': 1,
   'file_name': '20240524_213212_jpg.rf.378396a27d951e4397d95f480202583a.jpg',
   'height': 640,

In [54]:
df_nd=pd.DataFrame(nd['annotations'])
df_nd

,id,image_id,category_id,bbox,area,segmentation,iscrowd
0,0,0,2,"[483, 69, 71, 85.333]",6058.667,"[[514, 154.667, 537, 136, 554, 104, 546, 80, 5...",0
1,1,0,2,"[384, 365, 81, 124]",10044.000,"[[403, 481.333, 414, 489.333, 438, 460, 464, 4...",0
2,2,0,3,"[196, 271, 54.817, 364.578]",19985.188,"[[222.275, 630.94, 211.795, 575.017, 211.795, ...",0
3,3,1,2,"[103, 99, 92.095, 97.015]",8934.563,"[[102.941, 140.725, 113.847, 169.829, 127.782,...",0
4,4,1,1,"[459, 4, 180.606, 357.338]",64537.389,"[[640, 244.207, 539.785, 4.096, 522.215, 29.96...",0
...,...,...,...,...,...,...,...
523,523,270,3,"[49, 0, 282.679, 94.29]",26653.705,"[[49.23, 0, 98.936, 55.573, 160.203, 86.761, 2...",0
524,524,271,2,"[187, 309, 67.859, 112.375]",7625.724,"[[190.794, 373.561, 204.73, 377.603, 210.183, ...",0
525,525,271,2,"[524, 391, 71.495, 105.908]",7571.838,"[[577.956, 411.558, 561.597, 391.347, 543.03, ...",0
526,526,272,2,"[205, 392, 99, 129.333]",12804.000,"[[261, 393.333, 248, 392, 216, 397.333, 205, 4...",0
527,527,272,2,"[535, 405, 84, 138.667]",11648.000,"[[535, 453.333, 548, 517.333, 556, 537.333, 56...",0

In [55]:
df_nd_images=pd.DataFrame(nd['images'])
df_nd_images

,id,license,file_name,height,width,date_captured
0,0,1,20240524_213028_jpg.rf.e3c7960bcf16ee8f775287e...,640,640,2024-07-20T03:26:41+00:00
1,1,1,20240524_205743_jpg.rf.ebcc27d5f99c602c17cedcb...,640,640,2024-07-20T03:26:41+00:00
2,2,1,20240524_213016_jpg.rf.ef9d8435863084fa859ed32...,640,640,2024-07-20T03:26:41+00:00
3,3,1,20240524_205838_jpg.rf.e3cb570d6bfbd39cced27d5...,640,640,2024-07-20T03:26:41+00:00
4,4,1,20240524_212919_jpg.rf.e142a217cc44e1037fef4fd...,640,640,2024-07-20T03:26:41+00:00
...,...,...,...,...,...,...
268,268,1,20240524_213222_jpg.rf.d77f2adc78b1ebe6ad29607...,640,640,2024-07-20T03:26:41+00:00
269,269,1,20240524_212124_jpg.rf.ddee61e8a6349286e6d7aac...,640,640,2024-07-20T03:26:41+00:00
270,270,1,20240524_213400_jpg.rf.de9ae3c51494ad5ef83614d...,640,640,2024-07-20T03:26:41+00:00
271,271,1,20240524_205726_jpg.rf.da975940fdca4769ca13f49...,640,640,2024-07-20T03:26:41+00:00
272,272,1,20240524_212203_jpg.rf.dcd4f17142324c081513e2c...,640,640,2024-07-20T03:26:41+00:00

In [56]:
df_nd_inf=pd.DataFrame(nd['categories'])
df_nd_inf

   id                     name            supercategory
0   0  Bridge-Particle-Scratch                     none
1   1                   bridge  Bridge-Particle-Scratch
2   2                 particle  Bridge-Particle-Scratch
3   3                  scratch  Bridge-Particle-Scratch

In [57]:
# Dataset 1 category name → unified class
d1_class_map = {
    "block etch": "open_etch",
    "coating bad": "coating_defect",
    "particle": "particle",
    "piq particle": "particle",
    "po contamination": "po_contamination",
    "scratch": "scratch",
    "sez burnt": "thermal_damage"
}

# dataset 2 category name → unified class
d2_class_map = {
    "bridge": "bridge",
    "particle": "particle",
    "scratch": "scratch"
}

In [58]:
unified_classes = [
    "open_etch",
    "coating_defect",
    "particle",
    "po_contamination",
    "scratch",
    "bridge",
    "thermal_damage"
]

In [59]:
def merge_coco_datasets(d1: dict, d2: dict) -> dict:
    unified_categories = []
    class_name_to_id = {}

    for idx, name in enumerate(UNIFIED_CLASSES):
        unified_categories.append({
            "id": idx,
            "name": name,
            "supercategory": "defect"
        })
        class_name_to_id[name] = idx

    def build_cat_id_map(categories, class_map):
        cat_id_to_unified = {}
        for c in categories:
            if c["name"] in class_map:
                unified_name = class_map[c["name"]]
                cat_id_to_unified[c["id"]] = class_name_to_id[unified_name]
        return cat_id_to_unified

    d1_cat_map = build_cat_id_map(d1["categories"], D1_CLASS_MAP)
    d2_cat_map = build_cat_id_map(d2["categories"], D2_CLASS_MAP)

    merged_images = []
    image_id_offset = 0

    d1_img_id_map = {}
    for img in d1["images"]:
        new_img = img.copy()
        new_img["id"] = image_id_offset
        d1_img_id_map[img["id"]] = image_id_offset
        merged_images.append(new_img)
        image_id_offset += 1

    d2_img_id_map = {}
    for img in d2["images"]:
        new_img = img.copy()
        new_img["id"] = image_id_offset
        d2_img_id_map[img["id"]] = image_id_offset
        merged_images.append(new_img)
        image_id_offset += 1

    merged_annotations = []
    ann_id = 0

    def add_annotations(annotations, img_map, cat_map):
        nonlocal ann_id
        for ann in annotations:
            if ann["category_id"] not in cat_map:
                continue

            new_ann = ann.copy()
            new_ann["id"] = ann_id
            new_ann["image_id"] = img_map[ann["image_id"]]
            new_ann["category_id"] = cat_map[ann["category_id"]]
            merged_annotations.append(new_ann)
            ann_id += 1

    add_annotations(d1["annotations"], d1_img_id_map, d1_cat_map)
    add_annotations(d2["annotations"], d2_img_id_map, d2_cat_map)

    merged_coco = {
        "info": {
            "year": "2024",
            "version": "merged_v1",
            "description": "Merged wafer defect datasets (D1 + D2)",
        },
        "licenses": d1.get("licenses", []),
        "categories": unified_categories,
        "images": merged_images,
        "annotations": merged_annotations
    }

    return merged_coco

In [60]:
m=merge_coco_datasets(data, nd)
m
json.dump(m, open('merged_dataset.json', 'w'), indent=4)

In [61]:
import os
import cv2
import json
import random
import uuid
from collections import defaultdict


def extract_clean_patches(
    coco: dict,
    image_dir: str,
    output_dir: str,
    patch_size: int = 128,
    margin: int = 16,
    max_patches_per_image: int = 3
):
    """
    Extract defect-free (clean) patches using bounding-box exclusion.

    Args:
        coco: merged COCO dict
        image_dir: path to 'train' images
        output_dir: path to save 'clean' images
        patch_size: size of square clean patch
        margin: safety margin around defect bboxes
        max_patches_per_image: limit patches per image
    """

    os.makedirs(output_dir, exist_ok=True)

    # Group annotations by image_id
    anns_by_image = defaultdict(list)
    for ann in coco["annotations"]:
        anns_by_image[ann["image_id"]].append(ann["bbox"])

    image_count = 0
    saved_count = 0

    for img_info in coco["images"]:
        img_id = img_info["id"]
        img_path = os.path.join(image_dir, img_info["file_name"])

        if not os.path.exists(img_path):
            continue

        image = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if image is None:
            continue

        h, w = image.shape
        bboxes = anns_by_image.get(img_id, [])

        # Expand bboxes with margin
        forbidden = []
        for x, y, bw, bh in bboxes:
            x1 = max(0, int(x - margin))
            y1 = max(0, int(y - margin))
            x2 = min(w, int(x + bw + margin))
            y2 = min(h, int(y + bh + margin))
            forbidden.append((x1, y1, x2, y2))

        def is_clean(x1, y1, x2, y2):
            for fx1, fy1, fx2, fy2 in forbidden:
                if not (x2 <= fx1 or x1 >= fx2 or y2 <= fy1 or y1 >= fy2):
                    return False
            return True

        patches_found = 0
        attempts = 0
        max_attempts = 50

        while patches_found < max_patches_per_image and attempts < max_attempts:
            attempts += 1

            x1 = random.randint(0, w - patch_size)
            y1 = random.randint(0, h - patch_size)
            x2 = x1 + patch_size
            y2 = y1 + patch_size

            if not is_clean(x1, y1, x2, y2):
                continue

            patch = image[y1:y2, x1:x2]

            if patch.shape != (patch_size, patch_size):
                continue

            filename = f"clean_{img_id}_{uuid.uuid4().hex[:8]}.png"
            cv2.imwrite(os.path.join(output_dir, filename), patch)

            patches_found += 1
            saved_count += 1

        image_count += 1

    print(f"[INFO] Processed images: {image_count}")
    print(f"[INFO] Clean patches saved: {saved_count}")

In [62]:
import json

with open("merged_dataset.json", "r") as f:
    merged_coco = json.load(f)

extract_clean_patches(
    coco=merged_coco,
    image_dir="train",
    output_dir="clean_t",
    patch_size=128,
    margin=16,
    max_patches_per_image=3
)

[INFO] Processed images: 1872
[INFO] Clean patches saved: 3336